# backend/pytest.ini
[pytest]
# Tell pytest to look for tests in the 'app/tests' directory
testpaths = app/tests

# Tell pytest to add the current directory (.) to the python path.
# This makes imports like 'from app.db...' work correctly from any subdirectory.
pythonpath = .

# Use asyncio mode for all tests automatically
asyncio_mode = auto